// <auto-generated />
using System;
using Gb.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gb.Infrastructure.Migrations
{
    [DbContext(typeof(GbDbContext))]
    partial class GbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gb.Domain.DbEntities.CommentDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("Getutcdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("198009d2-bab7-4920-b80e-ea12503e2420"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John",
                            Text = "This is nice place!"
                        },
                        new
                        {
                            Id = new Guid("fcdb7df2-d708-4c37-bf34-bac22dea0e03"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ray",
                            Text = "Everything is fine"
                        },
                        new
                        {
                            Id = new Guid("f99e743d-d194-477f-aa29-07c5a0353a2d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alex",
                            Text = "This is the best place i have ever seen"
                        },
                        new
                        {
                            Id = new Guid("665c6d9b-c3f6-4333-a4a4-fe02a9394c0f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sam",
                            Text = "You should visit this place"
                        },
                        new
                        {
                            Id = new Guid("e3bbc408-09f9-4306-b45f-7d7cb1864c9f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James",
                            Text = "Not bad, everything is ok!"
                        },
                        new
                        {
                            Id = new Guid("11aeed30-8ded-4b46-ab21-ed7fd425c39a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ann",
                            Text = "Niccccccccccccccccceeeeeeeeeeeee"
                        },
                        new
                        {
                            Id = new Guid("33d24a8f-b9a5-4f55-9781-60b79d2c722a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jason",
                            Text = "This is nice place!"
                        },
                        new
                        {
                            Id = new Guid("a1e74d45-c4de-46ea-9589-91c7f2b86b03"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice",
                            Text = "This is the best place i have ever seen"
                        },
                        new
                        {
                            Id = new Guid("0b9faf0f-af06-4c28-9e28-f4b3713d1b01"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jim",
                            Text = "Everything is fine"
                        },
                        new
                        {
                            Id = new Guid("01328ed4-60cd-43bd-8691-ed9a0c300503"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jakob",
                            Text = "Not bad, everything is ok!"
                        },
                        new
                        {
                            Id = new Guid("e2353fbb-6920-4c32-9a99-9b50ffab2cc2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Susan",
                            Text = "You should visit this place"
                        },
                        new
                        {
                            Id = new Guid("1621d240-401d-4420-9393-0fbaba633f63"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ron",
                            Text = "Good place, i will come again"
                        },
                        new
                        {
                            Id = new Guid("a7add580-632e-4a53-83d1-df9bc8c983e2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Andy",
                            Text = "You should visit this place"
                        },
                        new
                        {
                            Id = new Guid("3c2db40f-92e9-4113-95c0-d7b2d6de7e9d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Enthony",
                            Text = "Good place, i will come again"
                        },
                        new
                        {
                            Id = new Guid("02e9970c-1927-49eb-bcb1-428b7b2d6d1f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bred",
                            Text = "This is nice place!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
